name: 'Hello docker action'
inputs:
  who-to-great:
    required: true
    default: 'world'
outputs:
  time:
    description: 'time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-great }}
